title: SEA Lab Docs
description: Static Site for hosting SEA Lab Docs
theme: just-the-docs

url: https://henrycikanek.github.io/sealab-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
